name: Shopify Theme Kit
description: Plain binary of Shopify Theme Kit for Github Actions
inputs:
  shopify-command:
    description: Command
    required: true
  shopify-flags:
    description: Flags
    default: ""
  working-directory:
    description: Working directory
    default: ""
runs:
  using: docker
  image: Dockerfile
  working-directory: ${{ inputs.working-directory }}
  args:
    - ${{ inputs.shopify-command }}
    - ${{ inputs.shopify-flags }}
